package com.github.spring_batch_smell_detector.model;

public enum SmellType {
	AMATEUR_WRITER, BRAIN_PROCESSOR, BRAIN_READER, 
	BRAIN_SERVICE, BRAIN_WRITER, GLOBAL_PROCESSOR,
	IMPROPER_COMMUNICATION, READAHOLIC_COMPONENT
}
